sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: AASREDzdXZRNtcVYfa1wHAl5oSXdJE2yyQspVHbD0aIJnmg1Zpo9W6goyc2lU/qMZc45SfuPH50cqNhaykRUDecr0Al/cCKMEtQC6d/uuneYWAg/xouozMIqU6IlBQBL+WiKKBnZZdzgGYg/t0NiFNrJc1Qi4vafSxfBz8XsrTczz0fZFgQSD7qFAvPHETH6z8dkFwSFY/blQUGBsf3eFOEXpAZpNOSXlhn7+mKAPwJnCpyF3ZBiOGoqgxbNpuJ8q1AZWzWUrwMCYoaRGhQKjkRiBXkl3YhAU9FZx6UDqKIFDqBpe8i5rct/R4UT3HcAOPRPGAfAxgDznGxa8jjlKw8H21eTrAcYbXDE76B1Zzx+IeDaYLDMgOWmiFQZ9nrLsPJLjg4j3X6P0CJ3tnItiTGDQdgmCM5JB372ed9NmGFVMW6IEod4fn+69wAsOaJS8yaTOMo0+WYjDBMEoUshV+5vFuYWM3R2h897tylsZUij9n6ocJY8I1BzW1mdpWBAvbn2JqNKGg8yuODmfn05C7Fi09qgv4ABZRsme3Whu0Uw+9rbkGW/qbdZBRfT3NZOcjv6ILuyeU+lxj8ksv0nu1BKAvwaRBiRjBwXYbRZbH5xBnpfldOYevTnLNIt3+X4oV73/gyvkCFg9IYq/ybOABFOwwecGojG/+MNPO4ns/k=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Variation-of-Animals-and-Plants-under-Domestication_3332
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy